mysql_dsn: "user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local"
server_port: ":8080"
base_url: "https://m.mixkomii.com"
allowed_origins: "http://localhost:3000"
allow_auto_migrate: false