// Code generated by MockGen. DO NOT EDIT.
// Source: service/shrt_handler.go
//
// Generated by this command:
//
//	mockgen -source=service/shrt_handler.go -destination=test/mocks/shrt_service_mock.go -package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	"shrt-server/types/request"
	types "shrt-server/types/response"

	gomock "go.uber.org/mock/gomock"
)

// MockShrtService is a mock of ShrtService interface.
type MockShrtService struct {
	ctrl     *gomock.Controller
	recorder *MockShrtServiceMockRecorder
}

// MockShrtServiceMockRecorder is the mock recorder for MockShrtService.
type MockShrtServiceMockRecorder struct {
	mock *MockShrtService
}

// NewMockShrtService creates a new mock instance.
func NewMockShrtService(ctrl *gomock.Controller) *MockShrtService {
	mock := &MockShrtService{ctrl: ctrl}
	mock.recorder = &MockShrtServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShrtService) EXPECT() *MockShrtServiceMockRecorder {
	return m.recorder
}

// CreateShrtLink mocks base method.
func (m *MockShrtService) CreateShrtLink(body *request.CreateShortenLinkRequest) (*types.CreateShortenLinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShrtLink", body)
	ret0, _ := ret[0].(*types.CreateShortenLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShrtLink indicates an expected call of CreateShrtLink.
func (mr *MockShrtServiceMockRecorder) CreateShrtLink(body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShrtLink", reflect.TypeOf((*MockShrtService)(nil).CreateShrtLink), body)
}

// GetOriginalURL mocks base method.
func (m *MockShrtService) GetOriginalURL(slug string) (*types.CreateShortenLinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURL", slug)
	ret0, _ := ret[0].(*types.CreateShortenLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalURL indicates an expected call of GetOriginalURL.
func (mr *MockShrtServiceMockRecorder) GetOriginalURL(slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURL", reflect.TypeOf((*MockShrtService)(nil).GetOriginalURL), slug)
}

// GetOriginalURLToRedirect mocks base method.
func (m *MockShrtService) GetOriginalURLToRedirect(slug string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURLToRedirect", slug)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalURLToRedirect indicates an expected call of GetOriginalURLToRedirect.
func (mr *MockShrtServiceMockRecorder) GetOriginalURLToRedirect(slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURLToRedirect", reflect.TypeOf((*MockShrtService)(nil).GetOriginalURLToRedirect), slug)
}
