// Code generated by MockGen. DO NOT EDIT.
// Source: utility/utility.go
//
// Generated by this command:
//
//	mockgen -source=utility/utility.go -destination=test/mocks/utility_mock.go -package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUtility is a mock of Utility interface.
type MockUtility struct {
	ctrl     *gomock.Controller
	recorder *MockUtilityMockRecorder
}

// MockUtilityMockRecorder is the mock recorder for MockUtility.
type MockUtilityMockRecorder struct {
	mock *MockUtility
}

// NewMockUtility creates a new mock instance.
func NewMockUtility(ctrl *gomock.Controller) *MockUtility {
	mock := &MockUtility{ctrl: ctrl}
	mock.recorder = &MockUtilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUtility) EXPECT() *MockUtilityMockRecorder {
	return m.recorder
}

// GenerateSlug mocks base method.
func (m *MockUtility) GenerateSlug() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSlug")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateSlug indicates an expected call of GenerateSlug.
func (mr *MockUtilityMockRecorder) GenerateSlug() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSlug", reflect.TypeOf((*MockUtility)(nil).GenerateSlug))
}
